version: "3"
services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
